language: php

dist: xenial

services:
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy

env:
  global:
    - COMPOSER_ROOT_VERSION=dev-master

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.5.x-dev PHPUNIT_TEST=1 MAINTENANCE=^2
    - php: 7.2
      env: DB=PGSQL RECIPE_VERSION=4.6.x-dev PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: DB=PGSQL RECIPE_VERSION=4.6.x-dev PHPUNIT_TEST=1
    - php: 7.4
      env: DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1 MAINTENANCE=2.x-dev

before_script:
  # Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini || true

  - composer require --no-update silverstripe/recipe-cms "$RECIPE_VERSION"
  # Fix for running phpunit 5 on php 7.4+
  - composer require --no-update sminnee/phpunit-mock-objects:^3
  - if [[ $MAINTENANCE ]]; then composer require --no-update bringyourownideas/silverstripe-maintenance:"$MAINTENANCE"; fi
  - if [[ $DB == PGSQL ]]; then composer require --no-update silverstripe/postgresql:^2; fi
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
